#nginx configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxthroughpass
data:
  default.conf: |-
    server {
            listen 80 default_server;
            root /var/www/html;
            server_name  _;
            index index.php;
            client_max_body_size 192m;
            location / {
                try_files $uri $uri/ /index.php?$args;
            }

            location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param   PATH_INFO       $fastcgi_path_info;
                fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param   PHP_VALUE       "memory_limit = 1024M;\n post_max_size = 192M;\n upload_max_filesize = 128M;\n file_uploads = On;\n max_execution_time = 600;\n max_input_time = 600";
                fastcgi_connect_timeout 300s;
                fastcgi_read_timeout 300s;
                fastcgi_send_timeout 300s;
            }
        }